@api_HostAddress = http://localhost:5170

#Employees
GET {{api_HostAddress}}/employees/
###
GET {{api_HostAddress}}/companies/


###
GET {{api_HostAddress}}/employees?company=CoMpany 8
###
GET {{api_HostAddress}}/companies?location=japan


###
GET {{api_HostAddress}}/employees/UIDzHYXLIRTKI
###
GET {{api_HostAddress}}/companies/e79bfa50-f680-4aa4-846f-66e57a6d1f79


###
#Employee
POST {{api_HostAddress}}/employee
Content-Type: application/json

{
    "name": "EmpForUp",
    "email": "test@test.test",
    "phone": "99999999",
    "gender": 1
}
###
POST {{api_HostAddress}}/company
Content-Type: application/json

{
    "name": "Company 11",
    "description": "Rank #11 in the world",
    "location": "Singapore"
}

###
GET {{api_HostAddress}}/employees/UIabWcNMtynha
###
PUT {{api_HostAddress}}/employee/UIabWcNMtynha
Content-Type: application/json

{
    "name": "EmpUpdated",
    "email": "updated@test.test",
    "phone": "88888878",
    "gender": 0,
    "photoUrl": null,
    "companyId": "0bfdaea4-b68f-44a1-ba2e-3f10371c43b1"
}


###
GET {{api_HostAddress}}/companies/e79bfa50-f680-4aa4-846f-66e57a6d1f79
###
PUT {{api_HostAddress}}/company/e79bfa50-f680-4aa4-846f-66e57a6d1f79
Content-Type: application/json

{
    "name": "Updated 11",
    "description": "Rank #11 in the world - updated",
    "location": "Singapore - updated"
}


###
DELETE  {{api_HostAddress}}/employee/UIKeBZnuAKU0b
###
DELETE  {{api_HostAddress}}/company/c6ed62d9-9f23-40c3-8967-967d8905f67b

###
